services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: carepoint_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - carepoint_postgres_data:/var/lib/postgresql/data
    container_name: carepoint-postgres

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=your_password
      - DB_NAME=carepoint
    command: npm run seed
    profiles:
      - seed

volumes:
  carepoint_postgres_data:
